# Generated by Django 2.0.7 on 2018-11-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facepresencehistory',
            unique_together={('face_id', 'workstation_id', 'minute_slot')},
        ),
    ]
