# Generated by Django 2.0.7 on 2018-07-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_blob', models.BinaryField(help_text='jpeg image')),
                ('awesomeness', models.DecimalField(decimal_places=5, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('face', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='recognitionapp.Face')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.SmallIntegerField(choices=[(1, 'arm guid'), (100, 'mailru vision')], null=True)),
                ('inner_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('face', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='recognitionapp.Face')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='providerid',
            unique_together={('provider', 'inner_id')},
        ),
    ]
