# Generated by Django 2.0.7 on 2018-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facephoto',
            name='wh',
            field=models.IntegerField(help_text='Площадь изображения в пикселях, для фильтрации мелких картинок', null=True),
        ),
    ]
