# Generated by Django 2.0.7 on 2018-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionapp', '0003_auto_20181101_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerid',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='providerid',
            name='inner_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
