# Generated by Django 2.0.7 on 2019-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionapp', '0004_remove_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='facephoto',
            name='workstation_id',
            field=models.CharField(help_text='С какой камеры/рабочего места это фото', max_length=36, null=True),
        ),
    ]
