build:
	cd camera_ocean  && make build
	cd face_recognition && make build
	cd object_detector && make build

migrations:
	cd face_recognition && make migrations

shell:
	cd face_recognition && make shell